apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql_metadata
spec:
  selector:
    matchLabels:
      app: postgresql_label
  template:
    metadata:
      labels:
        app: postgresql_template
    spec:
      containers:
        - name: postgresql_container
          image: postgres:16.2-alpine3.19
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_USER
              value: "kubenews"
            - name: POSTGRES_DB
              value: "kubenews_db"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql_service
spec:
  selector:
    app: postgresql_selector
  ports:
  - port: 5432
    targetPort: 5432

