apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-metadata
spec:
  selector:
    matchLabels:
      app: postgresql-labels
  template:
    metadata:
      labels:
        app: postgresql-labels
    spec:
      containers:
        - name: postgresql-container
          image: postgres:16.2-alpine3.19
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_USER
              value: "kubenews"
            - name: POSTGRES_DB
              value: "kubenews"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql-labels
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews-metadata
spec:
  selector:
    matchLabels:
      app: kubenews-labels
  template:
    metadata:
      labels:
        app: kubenews-labels
    spec:
      containers:
        - name: kubenews-container
          image: claysilva/kube-news
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATABASE
              value: kubenews
            - name: DB_USERNAME
              value: kubenews
            - name: DB_PASSWORD
              value: 1234
            - name: DB_HOST
              value: postgresql-service
---
apiVersion: v1
kind: Service
metadata:
  name: aplicacao-service
spec:
  selector:
    app: kubenews-labels
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
  type: NodePort
